name: UserManager
version: ${project.version}
main: com.aidanmurphey.usermanager.UserManager
authors: [Zee]
description: A plugin for managing the groups, permissions, and economy of a server
website: AidanMurphey.com
load: STARTUP

commands:
  balance:
    description: View your balance
    aliases: [bal]
    permission: um.balance
  pay:
    description: Send an amount of money to another player
    aliases: [sendmoney]
    permission: um.pay

permissions:
  um.balance:
    description: Gives access to /balance command
    default: true
  um.balance.others:
    description: Allows you to view the balance of others
    default: op
  um.pay:
    description: Gives access to /pay command
    default: true
