name: UserManager
version: ${project.version}
main: com.aidanmurphey.usermanager.UserManager
authors: [Zee]
description: A plugin for managing the groups, permissions, and economy of a server
website: AidanMurphey.com
load: STARTUP

commands:
  balance:
    description: View your balance
    aliases: [bal]
    permission: um.balance
    usage: /balance [player]
  pay:
    description: Send an amount of money to another player
    aliases: [sendmoney]
    permission: um.pay
    usage: /pay <player> <amount>
  balancetop:
    description: Lists the top 10 richest players in order
    aliases: [baltop]
    permission: um.baltop
    usage: /baltop
  economy:
    description: Manage the economy
    aliases: [eco]
    permission: um.economy
    usage: /eco <give|set|reset> <uuid> [amount]

permissions:
  um.balance:
    description: Gives access to /balance command
    default: true
  um.balance.others:
    description: Allows you to view the balance of others
    default: op
  um.pay:
    description: Gives access to /pay command
    default: true
  um.baltop:
    description: Gives access to /baltop command
    default: true
  um.economy:
    description: Gives access to /eco command
    default: op
